version: '3.7'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    ports:
      - 3001:3001
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    networks:
      - postgres-compose-network

  db:
    build: .docker/postgres
    restart: always
    tty: true
    container_name: postgres
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    ports:
      - '15432:5432'
    environment:
      POSTGRES_PASSWORD: '@Lab2019'
      POSTGRES_USER: dev
      POSTGRES_DB: apvBrasil
    networks:
      - postgres-compose-network

  redis:
    image: 'redis:alpine'
    volumes:
      - ./.docker/redisdata:/data
    ports:
      - '15442:6379'
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: 'bridge'
