export type Environments =
  | 'DATABASE_URL'
  | 'JWT_ACCESS_TOKEN_PRIVATE_KEY'
  | 'JWT_ACCESS_TOKEN_PUBLIC_KEY'
  | 'JWT_ACCESS_TOKEN_EXPIRATION_TIME'
  | 'JWT_REFRESH_TOKEN_PRIVATE_KEY'
  | 'JWT_REFRESH_TOKEN_PUBLIC_KEY'
  | 'JWT_REFRESH_TOKEN_EXPIRATION_TIME';
