POST http://localhost:3001/authentication/register HTTP/1.1
Content-Type: application/json

{
  "name": "David França",
  "password": "1234567",
  "username": "david.franca",
  "role": "ADMIN"
}

###
GET http://localhost:3001/users HTTP/1.1
